ONSdigital/ras-rm-docker-dev

- Makefile
- dev.yml
A new image, sdcplatform/dev-postgres has been created to include all
data generated by the integration test.  By default now, using these
compose files will spin up this postgres instance instead of the empty
one. Should now be possible to start developing/testing from a docker-compose.
NOTE: docker hub build for this needs to be working before this pull request is merged
> Now composes postgres image with ALL the data

- ras-services.yml
BACKSTAGE_API_URL has changed in ras-backstage to allow for v1/v2/v3
> Change backstage_api_url

- ras-services.yml
party host isn't added to the backstage configuration. Causing tests to fail in https://github.com/ONSdigital/ras-integration-tests/pull/33/files
> Add party host to backstage

- ras-services.yml
Since we don't have any docker instance of UAA running currently it makes sense to disable UAA when running response-operations-ui through docker
> Disable UAA by default

- ras-services.yml
- rm-services.yml
Adding healthcheck will inform developers when they `docker ps` whether
the services are running yet or not.
Output looks like:
> Add health checks to know services are running

- .env
- ras-services.yml
This change allows you to run backstage locally with the response-operations-ui docker container by setting the environment variable `export BACKSTAGE_HOST=docker.for.mac.host.internal` on mac or set to the machine's IP before `make up`. Previously you would have to edit the the `ras-services.yml` locally to achieve this.
> Added a backstage host variable to the environment for R-Ops-UI

- ras-services.yml
uploading a response sheet was failing as the collection instrument
service was missing config items for CASE_SERVICE_HOST and
RM_SURVEY_SERVICE_HOST meaning they were defaulting to localhost
(which doesn't work in the docker envs)
> add missing config for collection-instrument service

- ras-services.yml
- rm-services.yml
If services are unhealthy or have died then restart them. This should
resolve the issue with sample service dying because of the pycryto
extension as it will restart and should work the next time around.
> Restart unhealthy services

- Pipfile
- Pipfile.lock
- setup_database.py
This pr introduces a try / except block to setup_database.py that gracefully handles connection issues between the psycopg2 engine and the postgres database.
Exceptions are caught, a relevant line is printed to stdout and the script calls exit(0).
> Handle psycopg2 engine connection errors

- Makefile
Previously it would install all the packages apart from the dev ones.  There is a new retrying module
added to this that wasn't getting installed, causing a failure on a fresh build.
> Install all packages

- ras-services.yml
- uaa/uaa.yml
Config update for: https://github.com/ONSdigital/response-operations-ui/pull/163
Response operations should directly sign in with UAA.
https://trello.com/c/oodNbXR2/100-response-operations-ui-should-sign-in-directly-using-uaa-not-via-backstage
> edit config for UAA and response operations

- ras-local.yml
Update the mount point of the response-operations-ui volume to match the working directory ("/app") in the container (previously "/response-operations-ui").
- Checkout this and the response-operations-ui branch of the same 
- run `SERVICE=response-operations-ui make local`
Follows changes in PR: ONSdigital/response-operations-ui#172
> Update volume and working directory of response-operations-ui

- .gitignore
- Makefile
- diagrams/publish-collection-exercise.puml
This PR adds a plantuml sequence diagram for 'publish collection exercise' and the means to build it
No code has been changed but the Makefile has been updated
```
make diagrams
/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome diagrams/publish-collection-exercise.svg
```
Ensure diagram can be viewed
> Added plantuml sequence diagram for publishing a collection exercise

- README.md
The following error was raised by docker without first having run this network create command:
```
ERROR: Network rasrmdockerdev_default declared as external, but could not be found. Please create the network manually using `docker network create rasrmdockerdev_default` and try again.
```
Extra step to pre-requisite instructions in README
N/A
N/A
> Add docker network creation command to README

- .env
- ras-local.yml
- ras-services.yml
Following https://github.com/ONSdigital/response-operations-ui/pull/199 backstage can be removed from the docker environment.
- [Trello](https://trello.com/c/0lPdzRbt)
- ~[Remove config PR](https://github.com/ONSdigital/response-operations-ui/pull/199)~
- [Remove from pipeline PR](https://github.com/ONSdigital/ras-deploy/pull/31)
- [Remove from acceptance tests PR](https://github.com/ONSdigital/rasrm-acceptance-tests/pull/144)
> Remove backstage service

- rm-services.yml
Sample service has a class that polls every 1s in the that
generates a lot of logs. This makes it hard to see any logs of interest
through the other verbose logs.
It will cut out the example below every 1s
```
2018-06-29T12:26:48.36+0100 [APP/PROC/WEB/0] OUT {"created":"2018-06-29 11:26:48,361","service":"samplesvc","level":"INFO","event":"SampleUnitDistributor is in the house"}
2018-06-29T12:26:48.36+0100 [APP/PROC/WEB/0] OUT {"created":"2018-06-29 11:26:48,366","service":"samplesvc","level":"DEBUG","event":"retrieve sample units excluding []"}
2018-06-29T12:26:48.36+0100 [APP/PROC/WEB/0] OUT {"created":"2018-06-29 11:26:48,365","service":"samplesvc","level":"DEBUG","event":"Succeeded to obtain lock on samplesvc.sampleunit.distribution:global:lock"}
2018-06-29T12:26:48.36+0100 …
```
> Sample service lower logging

- uaa/uaa.yml
Currently, only the username and password are set up when the uaa_user is created through docker-dev.  Secure Message needs the also needs the firstname and lastname and logs out a key error if they're not present, along with the error `UAA didn't return all expected details`.  
This only affects dev environments using the uaa_user in response-ops  and there's no change in functionality but it's a pain when debugging, as you have to filter out loads of the UAA key errors.
The ras-deploy pipeline already sets the uaa_user up with full details so no change is needed there.
Added email, firstname and lastname for uaa_user.
- Run the services locally
- Send a secure message - you should see a lot of key errors and the message `UAA didn't return all expected details`
- `make down`, pull in …
> Add full details for uaa_user

- rm-services.yml
Previously the action service had no knowledge of the sample service.
Today, amidst it all, it does!
Configuration change in rm-services.yml which exposes the sample service to the knowledge of the action service. This is to ensure that when the action service makes a call to the sample service, it is able to retrieve sample attributes and expose them within the service.
1. Modify application-test.yml in rm-action-service: rabbitmq, redis, postgres to point to the main docker environment's own ports, rather than those used in docker-compose.
2. Run all the integration tests in action service - ensure there are no connection refused errors, particularly relating to the SampleSvcClientService.
> Added config to tell action service where to find sample service

- ras-services.yml
Does what it says on the tin. sdcplatform/respondent-home-ui:latest is now the Python rewrite.
> Remove branch name from image now that Python app is master

- .env
Tiny change to allow redirect from eQ when running locally.
`.env`
* Make sure the service isn't running `docker-compose -f ras-services.yml stop respondent-home-ui`
* Checkout this branch
* Bring up the service `docker-compose -f ras-services.yml up -d respondent-home-ui`
* Ensure that the link `http://localhost:9092` opens RH
> Tweak Respondent Home UI redirect URL

- ras-local.yml
Adds the Respondent Home UI service to the ras-local compose script to allow local changes to propagate to running containers.
New RH entry in ras-local.yml.
- `docker-compose -f ras-local.yml up respondent-home-ui`
- make changes to e.g.: app/templates/index.html
- see if changes visible on localhost:9092
> Add respondent home ui for local volume

- rm-services.yml
The action exporter will generate notification files and put them on a
SFTP server. This process happens on a cron schedule. To speed the
acceptance tests up we've changed this to every one second and changed
the logging to ignore verbosity from the scheduler.
Change action service to poll every second
1. `make up`
1. Connect remote debugger to action exporter (port 5141)
1. Stick a breakpoint on ExportScheduler#scheduleExport and check it's called every 1s
or
1. Set LOGGING_LEVEL_uk.gov.ons.ctp.response.action.export.scheduled=INFO in rm-services.yml
1. `make up`
2. Check logs for `Scheduled run start` every 1s
https://github.com/ONSdigital/rasrm-acceptance-tests/pull/154
> Action exporter to poll every 1s

- dev.yml
As found in this github issue the user id is 2000
https://github.com/travis-ci/travis-ci/issues/7995.
This allows the sftp service to write the files.
UID set to 2000
https://trello.com/c/Ii0xwuGt/225-add-acceptance-test-for-generating-notification-file
> Change user id to allow travis to write file

- rm-services.yml
Looks like Springboot services default basic auth to false. 
Added config to enable basic auth for java services.
Java services spun up with master branch allows access without basic auth.
Using this branch and hitting one of the java services `http://0.0.0.0:8151/actionplans` should prompt you for basic auth/ give 401.
> Enable basic auth for java services

- ras-local.yml
- ras-services.yml
A recent change was added run response-operations-social-ui. The `UAA_CLIENT_ID` will need to change to `response_operations_social` to match the credentials set in `uaa.yml`
* ras-services.yml
* ras-local.yml
* make up
* Try logging into response-operations-social-ui with the test uaa_user ID.
> Update UAA client ID for response-operations-social-ui

- setup_database.py
The changes for a bug fix in actionexporter service include using `gen_random_uuid` from the pgcrypto extension as a default value. As a result the setup file here which drops and recreates pgcrypto can't run unless it is `CASCADE` because of the dependency on the extension.
- Add CASCADE to dropping of pgcrypto in database setup
- Start up the services in docker dev on the action exporter address fix branches:
https://github.com/ONSdigital/rm-action-service/pull/116
https://github.com/ONSdigital/rm-actionsvc-api/pull/34
https://github.com/ONSdigital/rm-actionexporter-service/pull/66
- Run a `make down` and then `make up` again, the setup database step should still work
[Trello](https://trello.com/c/BNWyG8P1/260-bug200-addresses-are-not-being-updated-when-a-new-one-for-that-ru-is-being-upd …
> Add CASCADE to dropping of pgcrypto in database setup

- README.md
Small update to `README.md` to add a reminder to increase Docker's default memory usage to 16GiB+. This'll be helpful for anyone setting up for the first time
> Adding a helpful reminder about Docker memory requirements

- dev.yml
- ras-local.yml
- ras-services.yml
- rm-services.yml
~The ras/rm services always restart when docker starts, but the backing services do not.  This results in spinning only part of the system and having it all be totally useless.  This sort of thing should be an all or nothing proposition.~
Having all of the services start on machine startup wastes system resources, heats up your laptop, and makes switching between services (this and SDX for example) a pain.  Having the system only startup when you request it is probably the right thing to do.
- ~Added restart: always to the backing services~
- Removed all instances of restart:always
- reindented the file so it's consistent with others
Spin it up and see if it works!
> Remove restart: always from all services

- Makefile
- ras-local.yml
- ras-services.yml
We've moved to ras-rm-auth-service, so we can stop using the django-oauth-test service.
Removed the django service from the docker files so that we're running less containers
- Build the containers.  Make sure that the django service doesn't appear.
- Ensure the acceptance tests still pass.
> Remove django-oauth2-test service

- uaa/uaa.yml
This changes the default user on Response Operations to have a proper email `ons@ons.fake` that passes email validation. This was necessary as it'd fail validation when wanting to change the account's password.
Small change to the .yml
If you really want to test it, spin up `ras-rm-docker-dev` and then put in calls to UAA to check the user details. Alternatively, wait for the reset password work to be merged and then use that form to check a user exists with that email address.
> Change UAA yml file

- uaa/uaa.yml
The `response-operations` client requires `oauth.login` authorisation to do a password change for a user that's forgotten their password
> Change R-Ops UAA client to have OAuth login permissions

- .env
- README.md
- ras-local.yml
- ras-services.yml
A bunch of the names were inconsistent, some had -service at the end and some didnt' (`party-service` vs `frontstage` for example).  It was a pain to know how to turn off a container by name.
> Remove superfluous '-service' from certain services
